### ISSUE TITLE
Flashing failure?

### ISSUE THREAD

**Issue by michaeI** [sambuls/MarlinOnTrinus#8]
Hi, I am flashing my trinus using arduino uno. It completes the process but the trinus is dead after, and when connecting via simplify3D a random gibberish is spitted out in the console:

Attempting connection at /dev/cu.wchusbserial1410...
READ: þQJÿQBJPJpp$få]a>haÙzváJZôQÿQþ%x%@áéN>`}ÉjKa7.aCP..aCKa*váJJðQHBþQPJðQHBp|X_aÜ6áMcYÒ>A"Ü6W*M&Ô62K7&Ck62K&3BBøJBjú% %0¶JHá"Ua:BZI¸rNXá~G:ráB¤BüB¶azMà-þ3ñNp|4b6H9JpOF6BjC.tY8n>^aA'à]ppb~PH¸@áBnðÖ%X6Q#ð%Yþ**MMrG6d"p|@p|2AX6P*lBB¸QváJJ@á@\"váB¸JCJÿ[BCJÿ52:6XBômÉ8p|,
  Testing plaintext communication protocol...
  Testing binary communication protocol...
  Testing alternate communication protocols...
  Attempting RTS reset and trying again...
  Connection failed.

What am I doing wrong? 
reverting to Pango firmware through pango software works.

**Comment by sambuls** [comment]
Since you receive garbage I suspect that your trinus is not dead.
That garbage typically indicates a wrong baud rate.
Try changing your baud rate until the garbage is no more.

**Comment by michaeI** [comment]
That was it, baud rate 250000 was the right one :-)
I can see that new firmware did not solve the issue with the temperature - before firmware update trinus reported 58 degrees, now reports 50 degrees... still around 28 degrees too much.

**Comment by juvasquezo** [comment]
Hi michael, i've had a sort of problems ulploading the firmware to the trinus printer, if you'd like to help me i would be very grateful.
